name: Integration workflow

on:
  push:
    branches:
      - main
      - misc/sonar-qube
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew
        shell: bash

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test

      - name: Checkstyle (Code Style Checker)
        run: ./gradlew checkstyleMain

      - name: PMD (Linter)
        run: ./gradlew pmdMain pmdTest

      - name: Code Coverage
        run: ./gradlew jacocoTestCoverageVerification

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        run: ./gradlew build jacocoTestReport sonarqube --info
        env:
          # Needed to get some information about the pull request, if any
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}