name: Integration workflow

on:
  pull_request:
    branches: '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key-gradle: ${{ steps.cache-keys.outputs.gradle-key }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache Gradle packages
        id: cache-keys
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

  build_and_test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ needs.setup.outputs.cache-key-gradle }}

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and Test
        run: ./gradlew build test

      - name: Code Quality Checks
        run: ./gradlew checkstyleMain pmdMain pmdTest jacocoTestCoverageVerification